name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies on ubuntu
      run: |
          sudo apt-get update
          sudo apt-get install libortp-dev
          sudo apt-get install libmediastreamer-dev
          sudo apt-get install lua5.3
          sudo apt-get install lua5.3-dev
          sudo apt-get install liblua5.3 
          sudo apt-get install gdb
          
    - name: make
      run: |
           cd ./src
           make all
    - name: make check
      run: gdb -ex run lua_filter_demo --scb ../scripts/body1.lua  --scp ../scripts/preambula1.lua 
